Explicitly encode if an entity should be included in the picker buffer
vE5li/korangar pull request #162
Opened 2024-11-28 16:52 UTC by kokosha

After sorting the entities from back to front, the logic from picker ignoring first two elements need to be changed.

2024-11-28 18:35 UTC, hasenbanck requested changes
Can you also please update the commit message?

`Explicitly encode if an entity should be included in the picker buffer`

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/graphics/passes/picker/entity.rs
> +        // TODO: Pass the player size directly instead of hardcoding it here.
```rust
fn prepare(&mut self, device: &Device, instructions: &RenderInstruction) {
        self.instance_data.clear();
        self.draw_count = 0;

        if self.bindless_support {
            self.bump.reset();
            self.lookup.clear();

            let mut texture_views = Vec::with_capacity_in(self.draw_count, &self.bump);

            for instruction in instructions.entities.iter().filter(|instruction| instruction.pickerable) {
                self.draw_count += 1;
```

Let's simplify this like this.

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/graphics/passes/picker/entity.rs
> +            for instruction in instructions.entities.iter().filter(|instruction| instruction.pickerable == true) {
```rust
            for instruction in instructions.entities.iter().filter(|instruction| instruction.pickerable) {
                self.draw_count += 1;
```

Like above.

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/graphics/passes/picker/entity.rs
>              let mut texture_views = Vec::with_capacity_in(self.draw_count, &self.bump);
```suggestion
            let mut texture_views = Vec::with_capacity_in(instructions.entities.len(), &self.bump);
```

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/graphics/instruction.rs
> +    pub pickerable: bool,
Let's call this `add_to_picker`.

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/world/entity/mod.rs
> +    pub fn render(&self, instructions: &mut Vec<EntityInstruction>, camera: &dyn Camera, pickerable: bool) {
Let's also call this `add_to_picker`

2024-11-28 18:35 UTC, hasenbanck commented on korangar/src/world/map/mod.rs
> +        let mut is_current_player = true || include_self;
```rust
    #[cfg_attr(feature = "debug", korangar_debug::profile)]
    pub fn render_entities(&self, instructions: &mut Vec<EntityInstruction>, entities: &[Entity], camera: &dyn Camera) {
        entities.iter().enumerate().for_each(|(index, entity)| {
            entity.render(instructions, camera, index != 0);
        });
    }
```

We never call this function with "include_self==false"! So let's simplify it.

2024-11-28 20:06 UTC, kokosha commented on korangar/src/graphics/passes/picker/entity.rs
> +            for (index, instruction) in instructions.enumerate() {
Find a bug in non-bind mode and changed to correct the behavior

2024-11-29 07:27 UTC, hasenbanck approved these changes

2024-11-29 07:38 UTC, merged